version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8000:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: ExpuSebySiornIPHys
      WORDPRESS_DB_NAME: wp_compat
    volumes:
      # - wordpress:/var/www/html
      - .:/var/www/html

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wp_compat
      MYSQL_USER: admin
      MYSQL_PASSWORD: ExpuSebySiornIPHys
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: